/* ==========================================================
   Fiches descriptives pour les pop-ups du créateur d'agent.
   Résumés rédigés pour le Scriptorium (pas le texte du livre).
   ========================================================== */

/* ---------- Pouvoirs psychiques ----------
   vw = Valeur Warp, diff = difficulté, po = portée, du = durée, m = manifeste */
const POWER_INFO = {
  // Pouvoirs mineurs
  "Call Vermin":          { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Maintenu", d: "Prend le contrôle de la vermine alentour et la rassemble en essaim dans une zone, qui devient difficile à traverser (ou à voir si l'essaim vole). L'essaim peut être déplacé." },
  "Combustion":           { vw: 2, diff: "Routinier (+20)", po: "Moyenne", du: "Instantané", d: "Enflamme un objet inflammable. Si quelqu'un le tient ou le porte, il doit s'en débarrasser vite ou prendre feu." },
  "Dread Presence":       { vw: 2, diff: "Normal (+0)", po: "Soi", du: "Maintenu", m: true, d: "Une aura de terreur : les ennemis qui entrent dans votre zone ou y commencent leur tour risquent d'être effrayés par vous." },
  "Dull Pain":            { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Maintenu", d: "Anesthésie autant de créatures que vos DR : elles ne ressentent plus la douleur et gagnent 1 point d'armure partout." },
  "Float":                { vw: 2, diff: "Routinier (+20)", po: "Soi / contact", du: "Maintenu", m: true, d: "Vous flottez et vous déplacez lentement dans toutes les directions, ou vous allégez un objet touché." },
  "Ignite":               { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Maintenu", m: true, d: "Une petite flamme apparaît dans votre main, sans vous brûler et impossible à éteindre normalement." },
  "Ill Omen":             { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Maintenu", d: "Fait suinter le Warp dans une zone : vous choisissez un phénomène psychique parmi plusieurs tirages." },
  "Jinx":                 { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Instantané", d: "Maudit une créature : son prochain test dans l'heure se fait avec Désavantage." },
  "Luck":                 { vw: 1, diff: "Normal (+0)", po: "Soi", du: "Instantané", d: "Juste avant un test : réussi, vous le faites avec Avantage ; raté, avec Désavantage. Une fois par round, pas sur la Maîtrise psychique." },
  "Lull":                 { vw: 3, diff: "Difficile (−10)", po: "Courte", du: "Maintenu", d: "Endort une créature qui rate son test de Résistance. Plus dur sur quelqu'un en plein effort ou en combat." },
  "Nova":                 { vw: 3, diff: "Difficile (−10)", po: "Soi", du: "Instantané", m: true, d: "Une onde d'énergie frappe toute votre zone : 4 + BFM + DR de dégâts, et risque de renverser chacun." },
  "Preternatural Senses": { vw: 2, diff: "Routinier (+20)", po: "Soi", du: "Maintenu", d: "Vos sens dépassent ceux de votre espèce : vous ignorez l'obscurité et percevez bien plus loin." },
  "Psychic Scrutiny":     { vw: 1, diff: "Facile (+40)", po: "Courte", du: "Instantané", d: "Scrute l'âme d'une créature : chaque DR révèle une information sur son état (santé, émotions, intentions…)." },
  "Psychic Static":       { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Maintenu", d: "Un brouillage psychique vous rend difficile à remarquer, pour les créatures comme pour les appareils." },
  "Scalding Glance":      { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Maintenu", d: "Fait bouillir instantanément une quantité de liquide proportionnelle à vos DR." },
  "Seal Wounds":          { vw: 2, diff: "Routinier (+20)", po: "Contact", du: "Instantané", m: true, d: "Accélère la guérison d'une créature touchée (vous compris) et lui rend des Blessures." },
  "Sear":                 { vw: 3, diff: "Difficile (−10)", po: "Moyenne", du: "Maintenu", d: "Rend un objet brûlant et rougeoyant : difficile de le garder en main." },
  "Smite":                { vw: 2, diff: "Difficile (−10)", po: "Moyenne", du: "Instantané", m: true, d: "Une décharge d'énergie warp brute : 2 + BFM + DR de dégâts qui ignorent l'armure." },
  "Soulsight":            { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Maintenu", d: "Sent les âmes alentour : selon les DR, combien de créatures, de quelles espèces et où elles se trouvent." },
  "Spasm":                { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Maintenu", d: "Une créature qui rate son test de Résistance perd temporairement l'usage d'un membre." },
  "Spectral Hands":       { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Maintenu", d: "Manipule à distance des objets légers, comme avec des mains invisibles." },
  // Biomancie
  "Affliction":           { vw: 3, diff: "Difficile (−10)", po: "Courte", du: "Maintenu", d: "Dérègle le corps d'une créature, qui subit un état handicapant si elle rate son test de Résistance." },
  "Bio-Lightning":        { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Instantané", m: true, d: "Un arc électrique frappe une cible et ceux qui l'entourent." },
  "Cleanse":              { vw: 3, diff: "Difficile (−10)", po: "Contact", du: "Instantané", m: true, d: "Purge le poison, l'étourdissement ou la maladie d'une créature touchée." },
  "Ferrocrete Flesh":     { vw: 3, diff: "Normal (+0)", po: "Contact", du: "Maintenu", m: true, d: "Durcit la peau, la chair et les os d'une créature touchée pour la rendre bien plus résistante." },
  "Haemorrhage":          { vw: 2, diff: "Normal (+0)", po: "Courte", du: "Instantané", d: "Rompt les vaisseaux sanguins d'une créature, qui se met à saigner abondamment." },
  "Iron Limb":            { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Maintenu", m: true, d: "Gonfle vos muscles : Avantage aux tests de Force et de Capacité de Combat." },
  "Life Leech":           { vw: 4, diff: "Très ardu (−30)", po: "Moyenne", du: "Maintenu", m: true, d: "Aspire la vitalité d'une créature comme un parasite." },
  "Metabolic Overdrive":  { vw: 2, diff: "Normal (+0)", po: "Courte", du: "Maintenu", m: true, d: "Accélère le métabolisme de plusieurs créatures, qui deviennent plus rapides et plus vives." },
  "Shape Flesh":          { vw: 1, diff: "Facile (+40)", po: "Contact", du: "Permanent", m: true, d: "Remodèle en dix minutes l'apparence d'une créature : traits, peau, voire silhouette selon les DR." },
  "Wither":               { vw: 2, diff: "Routinier (+20)", po: "Soi", du: "Instantané", m: true, d: "Une vague entropique dessèche les êtres vivants de votre zone." },
  // Divination
  "Armour Bane":          { vw: 2, diff: "Normal (+0)", po: "Courte", du: "Maintenu", d: "Guide une arme vers les failles des armures : elle devient Perforante selon vos DR." },
  "Dowsing":              { vw: 3, diff: "Difficile (−10)", po: "Spéciale", du: "Maintenu", d: "Remonte les fils du Warp jusqu'à un objet ou une créature que vous avez déjà vu." },
  "Forewarning":          { vw: 2, diff: "Routinier (+20)", po: "Soi", du: "Maintenu", d: "Des visions vous préviennent du danger : vous pouvez esquiver gratuitement." },
  "Perfect Timing":       { vw: 2, diff: "Normal (+0)", po: "Courte", du: "Instantané", d: "Étire le temps pour quelques alliés, qui ont le loisir de mieux préparer leur prochaine action." },
  "Prescience":           { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Spéciale", d: "Une transe pendant un repos pour entrevoir les futurs possibles et s'y préparer." },
  "Question the Warp":    { vw: 1, diff: "Normal (+0)", po: "Soi", du: "1 minute", m: true, d: "Une transe pour interroger le Warp sur une question. Il sait tout… mais il ment volontiers." },
  "Psychometry":          { vw: 1, diff: "Facile (+40)", po: "Contact", du: "1 minute", m: true, d: "Lit les émotions imprégnées dans un objet ou un lieu : de vagues impressions jusqu'à des visions précises." },
  "Scrying Gaze":         { vw: 1, diff: "Facile (+40)", po: "Spéciale", du: "1 minute", m: true, d: "Observe à distance une créature, un objet ou un lieu déjà vu, où qu'il soit." },
  "Twist Fate":           { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Instantané", d: "Inverse le sort d'un test fait avec Avantage ou Désavantage." },
  "Watchward":            { vw: 2, diff: "Routinier (+20)", po: "Soi", du: "Maintenu", d: "Sent si on vous observe, et selon les DR, combien, comment et d'où." },
  // Pyromancie
  "Cauterise":            { vw: 3, diff: "Difficile (−10)", po: "Contact", du: "Instantané", m: true, d: "Un éclair de chaleur maîtrisé arrête un saignement ou ramène un allié sonné à lui." },
  "Command Flames":       { vw: 3, diff: "Difficile (−10)", po: "Longue", du: "Instantané", d: "Dirige, attise ou étouffe les flammes à portée, autant de fois que vos DR." },
  "Fire Storm":           { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Instantané", m: true, d: "Une explosion de feu warp ravage toute une zone." },
  "Inferno":              { vw: 3, diff: "Ardu (−20)", po: "Longue", du: "Maintenu", m: true, d: "Embrase plusieurs zones (selon vos DR) en brasiers infernaux." },
  "Molten Beam":          { vw: 3, diff: "Ardu (−20)", po: "Longue", du: "Instantané", m: true, d: "Un rayon de chaleur digne d'un fuseur, qui transperce armure et chair." },
  "Plasma Torch":         { vw: 2, diff: "Normal (+0)", po: "Soi", du: "Maintenu", m: true, d: "Votre main s'entoure de plasma : de quoi découper, souder ou brûler au contact." },
  "Pyrelight":            { vw: 3, diff: "Ardu (−20)", po: "Spéciale", du: "Maintenu", m: true, d: "Votre corps irradie lumière et chaleur, éclairant votre zone." },
  "Smouldercloud":        { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Maintenu", m: true, d: "Remplit plusieurs zones de fumée et de vapeur épaisses qui bloquent la vue." },
  "Sunburst":             { vw: 2, diff: "Normal (+0)", po: "Longue", du: "Instantané", m: true, d: "Un éclair aveuglant dans une zone : yeux et capteurs en souffrent." },
  "Thermal Shroud":       { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Maintenu", m: true, d: "Protège vos alliés proches des dégâts du feu et de la chaleur." },
  // Télékinésie
  "Abjuration Mechanicum":{ vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Instantané", d: "Sabote une machine (ou un serviteur) : de simples ratés jusqu'à la panne complète selon les DR." },
  "Breach":               { vw: 2, diff: "Normal (+0)", po: "Moyenne", du: "Instantané", d: "Déchire un objet : une vitre, une porte, voire bien plus solide selon les DR." },
  "Crush":                { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Maintenu", d: "Une pression télékinétique broie et immobilise une créature : 3 + BFM + DR de dégâts." },
  "Deflection":           { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Maintenu", m: true, d: "Dévie coups et projectiles : armure supplémentaire partout égale à vos DR." },
  "Gate of Infinity":     { vw: 2, diff: "Normal (+0)", po: "1 mile par DR", du: "Maintenu", m: true, d: "Ouvre un passage à travers le Warp entre deux points éloignés." },
  "Gravity Well":         { vw: 1, diff: "Facile (+40)", po: "Soi", du: "Maintenu", m: true, d: "Alourdit tout autour de vous : votre zone devient difficile à traverser et à quitter." },
  "Impel":                { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Instantané", d: "Projette violemment un objet ou une créature dans une zone voisine." },
  "Psychic Barrier":      { vw: 3, diff: "Difficile (−10)", po: "Moyenne", du: "Maintenu", d: "Dresse un mur ou une bulle invisible qui bloque la matière et l'énergie." },
  "Psychic Maelstrom":    { vw: 2, diff: "Routinier (+20)", po: "Soi", du: "Maintenu", m: true, d: "Un tourbillon de force autour de vous frappe ceux qui entrent dans votre zone." },
  "Vortex of Doom":       { vw: 4, diff: "Très ardu (−30)", po: "Moyenne", du: "Maintenu", m: true, d: "Ouvre une plaie dans la réalité qui dévaste une zone. Extrêmement dangereux, y compris pour vous." },
  // Télépathie
  "Beacon":               { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Maintenu", d: "Accroche votre esprit à une créature pour connaître en permanence sa position et ses mouvements." },
  "Compel":               { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Instantané", d: "Un ordre psychique simple qu'une créature doit exécuter si elle perd l'opposition." },
  "Dominate":             { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Maintenu", d: "Prend le contrôle d'une créature qui perd son test de Discipline." },
  "Erasure":              { vw: 2, diff: "Routinier (+20)", po: "Courte", du: "Instantané", d: "Efface un souvenir précis de l'esprit d'une créature." },
  "Mental Interrogation": { vw: 2, diff: "Normal (+0)", po: "Courte", du: "Maintenu", d: "Fouille la mémoire d'une créature : pensées de surface, puis secrets de plus en plus profonds selon les DR." },
  "Nightshroud":          { vw: 2, diff: "Normal (+0)", po: "Soi", du: "Maintenu", m: true, d: "Une illusion d'ombres plonge votre zone dans le noir pour vos ennemis, pas pour vos alliés." },
  "Psychic Fortitude":    { vw: 3, diff: "Ardu (−20)", po: "Courte", du: "Maintenu", d: "Prête votre volonté à vos alliés, qui peuvent utiliser votre Force Mentale." },
  "Psychic Shriek":       { vw: 3, diff: "Difficile (−10)", po: "Moyenne", du: "Instantané", m: true, d: "Un cri silencieux qui déchire les âmes dans deux zones." },
  "Telepathic Link":      { vw: 3, diff: "Ardu (−20)", po: "Longue", du: "Maintenu", d: "Relie mentalement plusieurs alliés pour communiquer en silence." },
  "Terrifying Visions":   { vw: 3, diff: "Ardu (−20)", po: "Moyenne", du: "Maintenu", d: "Confronte une créature à ses pires cauchemars : elle risque d'être terrifiée." },
};

/* ---------- Équipement ----------
   t = type, s = caractéristiques chiffrées (repères), d = description */
const ITEM_INFO = {
  // Armes de mêlée
  "Couteau":                       { t: "Arme de mêlée", s: "Dég. 0 + BF · Discret, Lancer", d: "Petit, discret, toujours utile. Se lance à courte portée." },
  "2 couteaux":                    { t: "Armes de mêlée", s: "Dég. 0 + BF chacun · Discret, Lancer", d: "Deux couteaux : un à la main, un en réserve (ou à lancer)." },
  "Couteau (lame monomoléculaire)":{ t: "Arme de mêlée", s: "Dég. 0 + BF · modification lame monomoléculaire", d: "Un couteau dont le tranchant aiguisé à l'extrême perce mieux les protections." },
  "Bâton":                         { t: "Arme de mêlée", s: "Dég. 1 + BF · Défensif, Deux mains", d: "Simple et défensif : Avantage pour parer en mêlée." },
  "Bâton ornemental":              { t: "Arme de mêlée", s: "Dég. 1 + BF · Défensif, Deux mains · Ornemental", d: "Un bâton richement décoré, signe de rang dans l'Ecclésiarchie." },
  "Épée tronçonneuse":             { t: "Arme de mêlée", s: "Dég. 3 + BF · Bruyant, Lacération (2)", d: "Des dents rotatives qui déchiquettent chair et armure, dans un vacarme terrible." },
  "Grande arme":                   { t: "Arme de mêlée", s: "Dég. 4 + BF · Lourd (4), Deux mains", d: "Marteau, hache ou épée à deux mains : dévastatrice, mais il faut de la force (BF 4)." },
  "Arme de mêlée ordinaire":       { t: "Arme de mêlée", s: "Selon l'arme (épée 2 + BF, hache 2 + BF, masse 2 + BF…)", d: "Une arme commune au choix : épée, hache, masse, fléau…" },
  "Une arme ordinaire et un outil courant (piètre qualité, laids)": { t: "Équipement", s: "Défauts : piètre qualité, laid", d: "Ce qu'on trouve dans la rue : une arme ordinaire et un outil commun au choix, abîmés et peu présentables." },
  // Armes à distance
  "Pistolet laser":                { t: "Arme à distance", s: "Dég. 5 · Portée moyenne · Rafale, Proche, Fiable", d: "L'arme de poing la plus répandue de l'Imperium : robuste et facile à recharger." },
  "Fusil laser":                   { t: "Arme à distance", s: "Dég. 6 · Portée longue · Rafale, Fiable, Deux mains", d: "Le fusil standard de la Garde impériale." },
  "Carabine laser":                { t: "Arme à distance", s: "Dég. 5 · Portée moyenne · Tir rapide, Fiable, Deux mains", d: "Un fusil laser raccourci, plus maniable en milieu fermé." },
  "Long-las":                      { t: "Arme à distance", s: "Dég. 6 · Portée extrême · Rafale, Perforant (1), Fiable", d: "Le fusil de précision laser des tireurs d'élite." },
  "Pistolet automatique":          { t: "Arme à distance", s: "Dég. 5 · Portée moyenne · Proche, Tir rapide (3)", d: "Un pistolet à balles capable d'arroser une cible." },
  "Pistolet à balles":             { t: "Arme à distance", s: "Dég. 6 · Portée moyenne · Rafale, Proche", d: "Un pistolet à projectiles simple et bon marché." },
  "Revolver":                      { t: "Arme à distance", s: "Dég. 6 · Portée moyenne · Proche, Fiable", d: "Six coups, un mécanisme qui ne s'enraye presque jamais." },
  "Fusil à pompe":                 { t: "Arme à distance", s: "Dég. 6 · Portée moyenne · Inflige (À terre), Dispersion", d: "À courte distance, il renverse sa cible et touche ses voisins." },
  "Fusil à pompe de combat":       { t: "Arme à distance", s: "Dég. 6 · Portée moyenne · Inflige (À terre), Dispersion · chargeur plus grand", d: "La version militaire du fusil à pompe, avec un gros chargeur." },
  "Fusil de précision":            { t: "Arme à distance", s: "Dég. 8 · Portée extrême · Bruyant, Deux mains", d: "Une arme à balles pour tirer de très loin." },
  "Lance-flammes de poing":        { t: "Arme à distance", s: "Dég. 7 · Portée courte · Proche, Flammes, Inflige (En feu)", d: "Un petit lance-flammes d'une main, pour purifier de près." },
  "Grenade frag":                  { t: "Explosif", s: "Dég. 6 · Lancer (moyenne) · Souffle, Instable", d: "Une gerbe d'éclats sur une zone : l'arme anti-personnel de base." },
  "Grenade fumigène":              { t: "Explosif", s: "Lancer (moyenne) · zone très obscurcie quelques rounds", d: "Un nuage épais qui bloque la vue (pas l'infrarouge)." },
  "Silencieux":                    { t: "Modification d'arme", s: "Armes à projectiles solides", d: "Étouffe le bruit des tirs d'une arme à balles." },
  // Armures
  "Robes":                         { t: "Armure simple", s: "Armure 1 · bras, torse, jambes · Discret", d: "Le vêtement des adeptes et des prêtres. Protège à peine, mais se cumule avec une autre armure." },
  "Robes ornementales":            { t: "Armure simple", s: "Armure 1 · Discret · Ornemental", d: "Des robes de cérémonie qui impressionnent les fidèles." },
  "Cuirs légers":                  { t: "Armure simple", s: "Armure 1 · bras, torse, jambes · Discret", d: "Des vêtements de cuir renforcés." },
  "Cuirs épais":                   { t: "Armure simple", s: "Armure 2 · bras, torse, jambes", d: "Du cuir épais, la protection des gangers et des chasseurs." },
  "Combinaison blindée":           { t: "Armure simple", s: "Armure 2 · bras, torse, jambes · Discret", d: "Une combinaison moulante renforcée, invisible sous les vêtements." },
  "Plaques de récupération":       { t: "Armure simple", s: "Armure 3 · torse · Lourd (3)", d: "Des plaques de métal récupérées et attachées tant bien que mal." },
  "Veste flak":                    { t: "Armure flak", s: "Armure 3 · bras, torse", d: "Une veste en plaques flak superposées." },
  "Gilet flak + bottes magnétiques": { t: "Armure flak + équipement", s: "Gilet : armure 3 au torse · Bottes : marcher en apesanteur", d: "La tenue de base des équipages de la Flotte." },
  "Armure flak de l'Astra Militarum": { t: "Armure flak", s: "Armure 4 · tout le corps · Bruyant", d: "L'armure complète réglementaire de la Garde impériale." },
  "Plastron de carapace":          { t: "Armure carapace", s: "Armure 6 · torse · Lourd (4), Bruyant", d: "Une plaque rigide très protectrice, mais lourde." },
  "Combinaison du vide":           { t: "Équipement de survie", s: "Ignore le vide spatial · bottes magnétiques intégrées", d: "Air, chaleur et pression pour survivre hors d'un vaisseau." },
  // Outils et équipement
  "Data-ardoise":                  { t: "Outil", s: "Commun", d: "Une tablette pour lire, stocker et transporter des données." },
  "Nécessaire d'écriture":         { t: "Outil", s: "Commun", d: "Plumes, encre et parchemins, là où la technologie fait défaut." },
  "Nécessaire d'écriture (piètre qualité)": { t: "Outil (origine)", s: "Piètre qualité", d: "Un nécessaire d'écriture usé, souvenir d'un monde féodal." },
  "Auto-plume":                    { t: "Outil", s: "—", d: "Transcrit automatiquement ce qui est dit." },
  "Trousse de chirurgien":         { t: "Outil médical", s: "Utilisations limitées", d: "Indispensable pour soigner de nombreuses blessures critiques." },
  "Outils de chirurgien":          { t: "Outil médical", s: "Utilisations limitées", d: "Le matériel nécessaire pour opérer et soigner les blessures graves." },
  "Enregistreur picte":            { t: "Outil", s: "—", d: "Capture des images, utiles comme preuves ou pour l'enquête." },
  "Vox-émetteur":                  { t: "Outil", s: "—", d: "Une radio portable à longue portée." },
  "Micro-vox":                     { t: "Outil", s: "Commun", d: "Une oreillette pour communiquer avec son équipe." },
  "Porte-voix":                    { t: "Outil", s: "—", d: "Amplifie la voix pour haranguer une foule ou donner des ordres sur un champ de bataille." },
  "Instrument de divination":      { t: "Objet psychique", s: "—", d: "Cartes, osselets ou cristaux : un support pour lire le Warp." },
  "Focus psychique":               { t: "Objet psychique", s: "Exotique", d: "Un objet personnel qui aide le psyker à canaliser son pouvoir." },
  "Fiole d'onguents sacrés":       { t: "Objet sacré", s: "—", d: "Des huiles bénies qui apaisent l'esprit des machines." },
  "Icône sacrée":                  { t: "Objet de foi", s: "Commun", d: "Un symbole de l'Empereur qui, pour un vrai croyant, a des effets bien réels." },
  "Bandoulières":                  { t: "Équipement", s: "—", d: "Des sangles pour porter armes et matériel à portée de main." },
  "Sac à dos":                     { t: "Équipement", s: "—", d: "De quoi transporter plus de matériel." },
  "Matériel de survie":            { t: "Équipement", s: "Commun", d: "Couverture, rations, gourde, allume-feu… pour tenir loin de la civilisation." },
  "Matériel de survie (piètre qualité)": { t: "Équipement (origine)", s: "Piètre qualité", d: "Un kit de survie rudimentaire de monde féral." },
  "Outil de tranchée":             { t: "Outil", s: "Peut servir d'arme improvisée", d: "Une pelle pliante pour creuser… ou cogner." },
  "Outil de tranchée (piètre qualité)": { t: "Outil (origine)", s: "Piètre qualité", d: "Une vieille pelle de monde agricole." },
  "Filtres respiratoires (laids)": { t: "Équipement (origine)", s: "Défaut : laid", d: "Des filtres pour supporter l'air vicié des ruches." },
  "Chrono":                        { t: "Équipement (origine)", s: "—", d: "Une montre : la ponctualité de la Schola Progenium." },
  "Bottes magnétiques (piètre qualité)": { t: "Équipement (origine)", s: "Piètre qualité", d: "Pour marcher sur les coques en apesanteur." },
  "Cape caméléoline":              { t: "Équipement", s: "Rare", d: "Une cape qui prend la couleur de son environnement." },
  "Découpeur laser":               { t: "Outil", s: "—", d: "Perce portes et cloisons, et sert de lampe." },
  "Photo-visières":                { t: "Équipement", s: "—", d: "Des lunettes pour voir dans l'obscurité." },
  "Globe lumineux":                { t: "Équipement", s: "—", d: "Une source de lumière portative." },
  "Menottes":                      { t: "Outil", s: "Commun", d: "Pour immobiliser un suspect." },
  "Auspex":                        { t: "Outil", s: "—", d: "Un scanner qui révèle ce qui se cache alentour." },
  "Perce-vox":                     { t: "Outil", s: "Rare", d: "Intercepte les communications vox." },
  "Multicompas":                   { t: "Outil", s: "Exotique", d: "Un instrument de navigation sophistiqué, utile partout dans le secteur." },
  "Kit de déguisement":            { t: "Outil", s: "Exotique", d: "Maquillage, perruques et prothèses pour se faire passer pour un autre." },
  "Grappin et corde":              { t: "Outil", s: "—", d: "Pour grimper et franchir les gouffres des ruches." },
  "Magnoculaires":                 { t: "Outil", s: "Commun", d: "Des jumelles pour observer de loin." },
  "Passe-partout":                 { t: "Outil", s: "—", d: "Aide à crocheter les serrures (avec Dextérité)." },
  "Brouilleur":                    { t: "Outil", s: "Rare", d: "Sature les transmissions dans la zone." },
  "Outil combiné":                 { t: "Outil", s: "—", d: "Un outil multifonction pour réparer et bricoler les machines." },
  "Diagnostor":                    { t: "Outil médical", s: "Rare", d: "Un scanner médical portatif, à combiner avec Médecine." },
  // Augmétiques
  "Matrice d'augures":             { t: "Augmétique", s: "Compte dans la limite d'augmétiques (BE)", d: "Des capteurs intégrés qui donnent les sens d'un auspex." },
  "Implant vocal":                 { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Une voix amplifiée et modulable, idéale pour prêcher ou commander." },
  "Système respiratoire augmétique": { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Des poumons mécaniques qui filtrent les gaz toxiques." },
  "Organe sensoriel augmétique":   { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Un œil ou une oreille artificiels, parfois meilleurs que l'original." },
  "Bras augmétique":               { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Un bras mécanique qui remplace l'original." },
  "Chenilles/roues augmétiques":   { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Des jambes remplacées par des chenilles ou des roues." },
  "Cœur augmétique":               { t: "Augmétique", s: "Compte dans la limite (BE)", d: "Un cœur mécanique qui aide à résister aux saignements." },
};

/* ---------- Descriptions des origines, factions et rôles ---------- */
const ORIGIN_DESC = {
  agri: "Une planète entière de champs et de silos pour nourrir les mondes-usines. On y forge des corps robustes, habitués au labeur sans fin.",
  feral: "Peu ou pas de technologie, une nature hostile : on y survit par la force. Ces mondes fournissent d'excellents guerriers à la Garde.",
  feodal: "Une société revenue à l'âge des seigneurs et des châteaux. Sa dîme se paie surtout en soldats.",
  forge: "Le domaine de l'Adeptus Mechanicus : usines, temples de données et air irrespirable. On y grandit au contact des machines sacrées.",
  ruche: "Des cités verticales de milliards d'âmes : les nobles en haut, le labeur au milieu, les gangs et les cultes dans les bas-fonds.",
  schola: "Orphelin d'un serviteur de l'Imperium, élevé par l'Ecclésiarchie dans une discipline de fer.",
  sanct: "Une planète sacrée couverte de basiliques, sous la coupe de l'Ecclésiarchie. Ses habitants sont fervents.",
  vide: "Né à bord d'un vaisseau ou d'une station, étranger aux planètes, à l'aise en apesanteur.",
};
const FACTION_DESC = {
  adm: "La bureaucratie titanesque qui fait tourner l'Imperium : dîmes, registres, archives. Un formulaire égaré peut condamner une planète.",
  tel: "Elle recense, forme et contrôle les psykers. Les plus forts servent l'Imperium sous surveillance, notamment comme astropathes.",
  mec: "Le culte de la machine, gardien des savoirs techniques. Ses prêtres remplacent leur chair par des augmentations.",
  min: "L'Ecclésiarchie, Église de l'Empereur-Dieu, qui prêche la foi sur des millions de mondes.",
  mil: "La Garde impériale : des milliards de soldats ordinaires levés sur tous les mondes.",
  flo: "La Marine impériale et les flottes marchandes, qui font circuler armées, commerce et dîme entre les étoiles.",
  inf: "Ceux qui vivent en marge de la société : contrebandiers, voleurs, gangs et cartels des bas-fonds.",
  inq: "Des agents aux pouvoirs presque illimités, chargés de traquer l'hérésie, les xenos et les démons.",
  rt: "Des familles munies d'une charte impériale qui les autorise à explorer et commercer au-delà des frontières.",
};
